package com.example.service

import android.accessibilityservice.AccessibilityService
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.SystemClock
import android.os.VibrationEffect
import android.os.Vibrator
import android.os.VibratorManager
import android.provider.Settings
import android.text.TextUtils
import android.util.Log
import android.view.accessibility.AccessibilityEvent
import com.example.data.repository.ReelRepository
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class TikTokReelAccessibilityService : AccessibilityService() {

    private val TAG = "TikTokReelService"
    private val serviceScope = CoroutineScope(Dispatchers.IO)
    private lateinit var repository: ReelRepository

    private var lastScrollTime = 0L
    private val DEBOUNCE_SCROLL_WINDOW_MS = 800L // Prevent multi-trigger on a single swipe fling

    private var lastReelTimestamp = 0L
    private var sessionReelCount = 0
    private var sessionStartTime = 0L
    private var currentForegroundPackage: String? = null

    override fun onCreate() {
        super.onCreate()
        repository = ReelRepository.getInstance(applicationContext)
    }

    override fun onServiceConnected() {
        super.onServiceConnected()
        _isServiceActive.value = true
        Log.i(TAG, "TikTok Reel Counter Accessibility Service connected")
    }

    override fun onAccessibilityEvent(event: AccessibilityEvent?) {
        if (event == null) return

        val packageName = event.packageName?.toString() ?: return

        // Verify if package is TikTok
        val isTikTok = TIKTOK_PACKAGES.contains(packageName)

        when (event.eventType) {
            AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED -> {
                if (isTikTok) {
                    if (currentForegroundPackage != packageName) {
                        // Started TikTok session
                        currentForegroundPackage = packageName
                        sessionStartTime = System.currentTimeMillis()
                        sessionReelCount = 0
                        lastReelTimestamp = sessionStartTime
                        _activeSessionReels.value = 0
                        _isTikTokInForeground.value = true
                    }
                } else {
                    if (currentForegroundPackage != null) {
                        // User exited TikTok
                        currentForegroundPackage = null
                        _isTikTokInForeground.value = false
                    }
                }
            }

            AccessibilityEvent.TYPE_VIEW_SCROLLED,
            AccessibilityEvent.TYPE_WINDOW_CONTENT_CHANGED -> {
                if (isTikTok) {
                    handlePossibleReelScroll(packageName, event)
                }
            }
        }
    }

    private fun handlePossibleReelScroll(packageName: String, event: AccessibilityEvent) {
        val now = SystemClock.uptimeMillis()

        // Debounce fast multi-events generated by a single vertical scroll gesture
        if (now - lastScrollTime < DEBOUNCE_SCROLL_WINDOW_MS) {
            return
        }

        // Check if event is a vertical scroll (scroll delta or scrollable container)
        val isVerticalScroll = event.scrollDeltaY != 0 ||
                (event.toIndex > 0 && event.fromIndex != event.toIndex) ||
                event.isScrollable

        if (isVerticalScroll || event.eventType == AccessibilityEvent.TYPE_VIEW_SCROLLED) {
            lastScrollTime = now

            val currentWallTime = System.currentTimeMillis()
            val dwellTimeSeconds = if (lastReelTimestamp > 0) {
                ((currentWallTime - lastReelTimestamp) / 1000).toInt().coerceIn(3, 120)
            } else {
                25
            }
            lastReelTimestamp = currentWallTime

            sessionReelCount++
            _activeSessionReels.value = sessionReelCount
            _lastReelScrolledTimestamp.value = currentWallTime

            serviceScope.launch {
                repository.recordReelScroll(
                    sourceApp = packageName,
                    dwellTimeSeconds = dwellTimeSeconds
                )
            }

            // Provide subtle haptic feedback
            triggerHapticFeedback()
            Log.d(TAG, "Counted TikTok reel scroll #$sessionReelCount (dwell: ${dwellTimeSeconds}s)")
        }
    }

    private fun triggerHapticFeedback() {
        try {
            val vibrator = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                val vibratorManager = getSystemService(Context.VIBRATOR_MANAGER_SERVICE) as? VibratorManager
                vibratorManager?.defaultVibrator
            } else {
                @Suppress("DEPRECATION")
                getSystemService(Context.VIBRATOR_SERVICE) as? Vibrator
            }

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                vibrator?.vibrate(VibrationEffect.createOneShot(20, VibrationEffect.DEFAULT_AMPLITUDE))
            } else {
                @Suppress("DEPRECATION")
                vibrator?.vibrate(20)
            }
        } catch (e: Exception) {
            // Ignore if vibration fails
        }
    }

    override fun onInterrupt() {
        Log.w(TAG, "Accessibility Service interrupted")
    }

    override fun onDestroy() {
        super.onDestroy()
        _isServiceActive.value = false
        _isTikTokInForeground.value = false
    }

    companion object {
        val TIKTOK_PACKAGES = setOf(
            "com.zhiliaoapp.musically", // Global TikTok
            "com.ss.android.ugc.trill", // TikTok Lite / Regional
            "com.ss.android.ugc.aweme"  // Douyin
        )

        private val _isServiceActive = MutableStateFlow(false)
        val isServiceActive: StateFlow<Boolean> = _isServiceActive.asStateFlow()

        private val _isTikTokInForeground = MutableStateFlow(false)
        val isTikTokInForeground: StateFlow<Boolean> = _isTikTokInForeground.asStateFlow()

        private val _activeSessionReels = MutableStateFlow(0)
        val activeSessionReels: StateFlow<Int> = _activeSessionReels.asStateFlow()

        private val _lastReelScrolledTimestamp = MutableStateFlow(0L)
        val lastReelScrolledTimestamp: StateFlow<Long> = _lastReelScrolledTimestamp.asStateFlow()

        fun isAccessibilitySettingsEnabled(context: Context): Boolean {
            val expectedComponentName = "${context.packageName}/${TikTokReelAccessibilityService::class.java.canonicalName}"
            val enabledServices = Settings.Secure.getString(
                context.contentResolver,
                Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES
            ) ?: return false

            val colonSplitter = TextUtils.SimpleStringSplitter(':')
            colonSplitter.setString(enabledServices)
            while (colonSplitter.hasNext()) {
                val component = colonSplitter.next()
                if (component.equals(expectedComponentName, ignoreCase = true) ||
                    component.contains(TikTokReelAccessibilityService::class.java.simpleName)
                ) {
                    return true
                }
            }
            return false
        }

        fun openAccessibilitySettings(context: Context) {
            try {
                val intent = Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS).apply {
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                context.startActivity(intent)
            } catch (e: Exception) {
                Log.e("TikTokReelService", "Could not open accessibility settings", e)
            }
        }
    }
}
